language: node_js
os:
- linux
node_js:
- lts/*
install:
- yarn install
script:
- yarn docs:build
branchs:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_e97faa040b4d_key -iv $encrypted_e97faa040b4d_iv -in deploy.enc -out ~/.ssh/deploy -d
- chmod 600 ~/.ssh/deploy
before_script:
- echo -e "Host ${ip}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- ssh -i ~/.ssh/deploy $user@$ip "echo $webroot"
- ssh -i ~/.ssh/deploy $user@$ip "echo ${webroot}"
- scp -i ~/.ssh/deploy -o stricthostkeychecking=no -rv .vuepress/dist/* $user@$ip:$webroot