language: node_js
os:
- linux
node_js:
- lts/*
install:
- yarn install
script:
- yarn docs:build
branchs:
  only:
  - master
addons:
  ssh_known_hosts: $ip
before_install:
- openssl aes-256-cbc -K $encrypted_e97faa040b4d_key -iv $encrypted_e97faa040b4d_iv -in deploy.enc -out ~/.ssh/deploy -d
- chmod 600 ~/.ssh/deploy
after_success:
- ssh $user@$ip "echo $webroot"
- ssh $user@$ip "echo ${webroot}"
- scp -i ~/.ssh/deploy -o stricthostkeychecking=no -rv .vuepress/dist/* $user@$ip:$webroot